learning_strategy:
  _target_: learning_strategies.evolution.loop.ESLoop
  offspring_strategy:
    _target_: learning_strategies.evolution.offspring_strategies.simple_gaussian_offspring
    elite_ratio: 0.1
    init_sigma: 2
    sigma_decay: 0.999
    offspring_num: 70
  env: 
    _target_: envs.gym_wrapper.GymWrapper
    env_name: CartPole-v0
    max_step: 200
  network:
    _target_: networks.neural_network.GymEnvModel
    num_state: 4
    num_action: 2
  cpu_num: 7