learning_strategy:
  _target_: learning_strategies.evolution.loop.ESLoop
  offspring_strategy:
    _target_: learning_strategies.evolution.offspring_strategies.simple_genetic
    init_sigma: 2
    sigma_decay: 0.999
    elite_num: 10
    offspring_num: 11
  env: 
    _target_: envs.gym_wrapper.GymWrapper
    env_name: LunarLander-v2
    max_step: 330
  network:
    _target_: networks.neural_network.GymEnvModel
    num_state: 8
    num_action: 4
  generation_num: 500
  cpu_num: 11